version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: rootpw
      POSTGRES_USER: root
      POSTGRES_DB: ctms

  server:
    build: 
      context: ../server
    ports:
      - 15000:5000
    depends_on:
      - db

  client:
    build:
      context: ../client
    ports:
      - 13000:3000
    depends_on:
      - server