###
GET http://localhost:15000/setup
###
GET http://localhost:15000/
###
POST http://localhost:15000/adduser
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.rest"
}
###
POST http://localhost:15000/
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.rest"
}
###
# Delete user with ID 1
DELETE http://localhost:15000/user/delete/5
###